# -*- coding: utf-8 -*-
"""index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZXbs86xSUdJZZYmr8aCuNzliXGUvGr6
"""

import json

issues = []

def handler(request):
    global issues

    if request.method == "GET" and request.path == "/api/issues":
        return {
            "statusCode": 200,
            "body": json.dumps(issues),
            "headers": {"Content-Type": "application/json"}
        }

    if request.method == "POST" and request.path == "/api/report":
        data = json.loads(request.body)
        issues.append({
            "id": len(issues) + 1,
            "title": data.get("title"),
            "location": data.get("location"),
            "status": "Pending"
        })
        return {
            "statusCode": 200,
            "body": json.dumps({"message": "ok"})
        }

    if request.method == "POST" and request.path == "/api/update":
        data = json.loads(request.body)
        for i in issues:
            if i["id"] == data.get("id"):
                i["status"] = data.get("status")

        return {
            "statusCode": 200,
            "body": json.dumps({"message": "updated"})
        }

    return {
        "statusCode": 404,
        "body": json.dumps({"error": "Not found"})
    }