# -*- coding: utf-8 -*-
"""index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZXbs86xSUdJZZYmr8aCuNzliXGUvGr6
"""

from http.server import BaseHTTPRequestHandler
import json

issues = []

class handler(BaseHTTPRequestHandler):

    def _set_headers(self):
        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

    def do_GET(self):
        if self.path == "/api/issues":
            self._set_headers()
            self.wfile.write(json.dumps(issues).encode())

    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length)
        data = json.loads(body)

        if self.path == "/api/report":
            issues.append({
                "id": len(issues) + 1,
                "title": data.get("title"),
                "location": data.get("location"),
                "status": "Pending"
            })

        elif self.path == "/api/update":
            for i in issues:
                if i["id"] == data.get("id"):
                    i["status"] = data.get("status")

        self._set_headers()
        self.wfile.write(json.dumps({"message": "OK"}).encode())

        from flask import Flask, request, jsonify

app = Flask(__name__)

issues = []

@app.route("/api/issues", methods=["GET"])
def get_issues():
    return jsonify(issues)

@app.route("/api/report", methods=["POST"])
def report():
    data = request.json
    issues.append({
        "id": len(issues) + 1,
        "title": data.get("title"),
        "location": data.get("location"),
        "status": "Pending"
    })
    return jsonify({"message": "ok"})

@app.route("/api/update", methods=["POST"])
def update():
    data = request.json
    for i in issues:
        if i["id"] == data.get("id"):
            i["status"] = data.get("status")
    return jsonify({"message": "updated"})

# THIS LINE IS CRITICAL
app = app